### ISSUE TITLE
Private Net-ID 172.x.x.x ist in nem größeren Bereich als im Code gefiltert

### ISSUE THREAD

**Issue by SteffoSpieler** [LubaLP/TJC_BotV2#1]
https://github.com/LubaLP/TJC_BotV2/blob/e37806aea80dd143a5693dc68390c21199336bfb/MODULES/AUTOMOD/LINKS.js#L98

Es gibt ja insgesammt 3 Private Klassen bei IPv4.

- 10.x.x.x -> Privat Klasse A (Filterst du raus)
- 172.16.x.x bis 172.31.x.x -> Privat Klasse B (Du filterst nur 172.18.x.x raus)
- 192.168.x.x -> Privat Klasse C (Filterst du raus)

**Comment by LubaLP** [comment]
Ja ich weiß ist im neuen Bot Code schon drin lass mich kurz gucken dann kann ich dir den neuen Code schicken

**Comment by LubaLP** [comment]
`if (parsedLink[0].match(/^\d/)) {
      // Whitelist von privaten (internen) Ips
      if (parsedLink.startsWith("192.168.") || parsedLink.startsWith("10.") || parsedLink.startsWith("127.")) {
          allowed = true;
      }
      else if (parsedLink.startsWith("172.") && parsedLink.split(".")[1] >= 16 && parsedLink.split(".")[1] <= 31) {
          allowed = true;
      } else {
          allowed = false;
      }
      resolve({"allowed": allowed, "link": parsedLink});
  }`

**Comment by SteffoSpieler** [comment]
na dann ist ja gut. Kann man dennoch hier fixen? xD
Falls keiner bock hat, kann ich ja ein Merge Request machen :D

**Comment by LubaLP** [comment]
ja klar wenn du Lust hast mach das gerne
Hier kannst dich austoben wenn es mir gefällt hau ich das in den Main Bot auch rein, also kannst theoretisch live an changes arbeiten die noch mit in den Bot reinfließen
